name: 'Publish Testim Test Results'
author: 'atlowChemi'
description: 'Report Testim test results as annotations on Github Pull Request [junit]'

branding:
    icon: 'check-circle'
    color: 'green'

inputs:
    github_token:
        description: 'GitHub API Access Token.'
        default: ${{ github.token }}
        required: false
    commit:
        description: 'Commit SHA to update the check status.'
        required: false
    job_name:
        description: 'Specify the name of a check to update'
        required: false
        default: ${{ github.job }}
    summary:
        description: 'Additional text to summary output'
        required: false
        default: ''
    check_name:
        description: 'Check name for test reports.'
        required: false
        default: 'Testim Test Report'
    report_paths:
        description: 'Xml report paths in glob format'
        required: false
        default: '**/junit-reports/TEST-*.xml'
    update_check:
        description: 'Defines if the active check should be updated instead'
        required: false
        default: 'false'
    require_tests:
        description: 'Fail if no test are found.'
        required: false
        default: 'false'
    fail_on_failure:
        description: 'Fail the build in case a test failure occurred.'
        required: false
        default: 'false'
    project_api_key_map:
        description: 'Dictionary of Testim API token and project.'
        required: false

runs:
    using: 'node16'
    main: 'lib/index.js'
